import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

interface Palette {
  [key: string]: string
  background: string
  surface: string
  foreground: string
  muted: string
  border: string
  accent: string
  raised: string
  overlay: string
  blue: string
  green: string
  peach: string
  red: string
  mauve: string
}

interface Tokens {
  latte: Palette
  mocha: Palette
  shape: Record<string, number>
  motion: Record<string, number>
}

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const tokens = JSON.parse(await readFile(resolve(root, 'tokens.json'), 'utf8')) as Tokens
const outputDirectory = resolve(root, 'generated')
await mkdir(outputDirectory, { recursive: true })

const cssPalette = (selector: string, palette: Palette) =>
  `${selector} {\n${Object.entries(palette)
    .map(([name, value]) => `  --luna-${name}: ${value};`)
    .join('\n')}\n}`
const css = `${cssPalette(':root, [data-theme="latte"]', tokens.latte)}\n\n${cssPalette('[data-theme="mocha"]', tokens.mocha)}\n`
await writeFile(resolve(outputDirectory, 'tokens.css'), css)

const swiftColor = (name: string, value: string) => {
  const red = Number.parseInt(value.slice(1, 3), 16) / 255
  const green = Number.parseInt(value.slice(3, 5), 16) / 255
  const blue = Number.parseInt(value.slice(5, 7), 16) / 255
  return `    static let ${name} = Color(red: ${red.toFixed(6)}, green: ${green.toFixed(6)}, blue: ${blue.toFixed(6)})`
}

const swiftPalette = (name: string, palette: Palette) =>
  `  enum ${name} {\n${Object.entries(palette)
    .map(([key, value]) => swiftColor(key, value))
    .join('\n')}\n  }`
const swift = `// Generated by @luna/design-tokens. Do not edit.\nimport SwiftUI\n\nenum LunaColors {\n${swiftPalette('Latte', tokens.latte)}\n\n${swiftPalette('Mocha', tokens.mocha)}\n}\n`
await writeFile(resolve(outputDirectory, 'LunaColors.swift'), swift)
