[package]
name = "luna-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
base64.workspace = true
directories.workspace = true
dotenvy.workspace = true
futures-util.workspace = true
http.workspace = true
image.workspace = true
luna-pi = { path = "../luna-pi" }
luna-protocol = { path = "../luna-protocol" }
luna-storage = { path = "../luna-storage" }
serde.workspace = true
rand.workspace = true
reqwest.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
http-body-util.workspace = true
tempfile.workspace = true
tokio-tungstenite.workspace = true
