/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @enum {string} */
    ActivityPhase: 'thinking' | 'working' | 'compacting' | 'retrying'
    AgentActivityChanged: {
      active: boolean
      phase: components['schemas']['ActivityPhase']
    }
    ApiError: {
      code: components['schemas']['ErrorCode']
      message: string
      requestId?: string | null
      retryable: boolean
    }
    Attachment: {
      /** Format: int64 */
      byteSize: number
      contentUrl: string
      createdAt: components['schemas']['String']
      fileName: string
      /** Format: int32 */
      height: number
      /** Format: uuid */
      id: string
      mimeType: string
      status: components['schemas']['AttachmentStatus']
      thumbnailUrl: string
      /** Format: int32 */
      width: number
    }
    AttachmentResponse: {
      attachment: components['schemas']['Attachment']
    }
    /** @enum {string} */
    AttachmentStatus: 'uploading' | 'ready' | 'attached' | 'failed' | 'deleted'
    Bootstrap: {
      conversations: components['schemas']['Conversation'][]
      /** Format: int64 */
      cursor: number
      device: components['schemas']['Device']
      /** Format: int32 */
      protocolVersion: number
    }
    ClientCommand:
      | (components['schemas']['ClientHello'] & {
          /** Format: int32 */
          version: number
        } & {
          /** @enum {string} */
          type: 'client.hello'
        })
      | (components['schemas']['MessageSendCommand'] & {
          /** Format: int32 */
          version: number
        } & {
          /** @enum {string} */
          type: 'message.send'
        })
      | (components['schemas']['SessionInterruptCommand'] & {
          /** Format: int32 */
          version: number
        } & {
          /** @enum {string} */
          type: 'session.interrupt'
        })
      | (components['schemas']['ClientPing'] & {
          /** Format: int32 */
          version: number
        } & {
          /** @enum {string} */
          type: 'client.ping'
        })
    ClientHello: {
      /** Format: uuid */
      deviceId: string
      /** Format: int64 */
      lastCursor: number
      /** Format: uuid */
      requestId: string
    }
    ClientPing: {
      /** Format: uuid */
      requestId: string
    }
    CommandAccepted: {
      message?: null | components['schemas']['Message']
      /** Format: uuid */
      requestId: string
    }
    CommandRejected: {
      error: components['schemas']['ApiError']
      /** Format: uuid */
      requestId: string
    }
    Conversation: {
      activeWorkingDirectory: string
      archivedAt?: null | components['schemas']['String']
      createdAt: components['schemas']['String']
      /** Format: uuid */
      id: string
      /** Format: uuid */
      notificationTargetDeviceId?: string | null
      preview: string
      repositories: components['schemas']['Repository'][]
      state: components['schemas']['SessionState']
      title: string
      titleMode: components['schemas']['TitleMode']
      /** Format: int64 */
      unreadCount: number
      updatedAt: components['schemas']['String']
      /** Format: int64 */
      version: number
    }
    ConversationList: {
      conversations: components['schemas']['Conversation'][]
    }
    ConversationMessages: {
      messages: components['schemas']['Message'][]
      /** Format: int64 */
      nextBeforeOrdinal?: number | null
    }
    ConversationTitleUpdated: {
      automatic: boolean
      title: string
    }
    CreateConversationRequest: Record<string, never>
    Device: {
      createdAt: components['schemas']['String']
      /** Format: uuid */
      id: string
      lastSeenAt: components['schemas']['String']
      name: string
      notificationsEnabled: boolean
      platform: components['schemas']['DevicePlatform']
    }
    /** @enum {string} */
    DevicePlatform: 'ios' | 'ipados' | 'web'
    /** @enum {string} */
    ErrorCode:
      | 'authentication_required'
      | 'forbidden'
      | 'invalid_request'
      | 'not_found'
      | 'conflict'
      | 'agent_unavailable'
      | 'agent_rejected'
      | 'attachment_invalid'
      | 'transcription_failed'
      | 'rate_limited'
      | 'internal_error'
    ErrorResponse: {
      error: components['schemas']['ApiError']
    }
    Message: {
      attachments: components['schemas']['Attachment'][]
      /** Format: uuid */
      clientMessageId?: string | null
      /** Format: uuid */
      conversationId: string
      createdAt: components['schemas']['String']
      delivery?: null | components['schemas']['MessageDelivery']
      /** Format: uuid */
      id: string
      /** Format: int64 */
      ordinal: number
      role: components['schemas']['MessageRole']
      /** Format: uuid */
      sentByDeviceId?: string | null
      status: components['schemas']['MessageStatus']
      text: string
      updatedAt: components['schemas']['String']
    }
    MessageCompleted: {
      /** Format: uuid */
      messageId: string
    }
    /** @enum {string} */
    MessageDelivery: 'initial' | 'steer'
    MessageDelta: {
      /** Format: int64 */
      chunkIndex: number
      delta: string
      /** Format: uuid */
      messageId: string
    }
    /** @enum {string} */
    MessageRole: 'user' | 'assistant'
    MessageSendCommand: {
      attachmentIds: string[]
      /** Format: uuid */
      clientMessageId: string
      /** Format: uuid */
      conversationId: string
      /** Format: uuid */
      requestId: string
      text: string
    }
    /** @enum {string} */
    MessageStatus:
      'pending' | 'accepted' | 'queued' | 'streaming' | 'completed' | 'interrupted' | 'failed'
    NotificationTargetChanged: {
      /** Format: uuid */
      deviceId: string
    }
    PairingExchangeRequest: {
      code: string
      deviceName: string
      platform: components['schemas']['DevicePlatform']
    }
    PairingExchangeResponse: {
      bootstrap: components['schemas']['Bootstrap']
      /** Format: uuid */
      deviceId: string
      token: string
    }
    RepositoriesUpdated: {
      repositories: components['schemas']['Repository'][]
    }
    Repository: {
      active: boolean
      branch?: string | null
      displayName: string
      firstSeenAt: components['schemas']['String']
      icon: components['schemas']['RepositoryIcon']
      /** Format: uuid */
      id: string
      lastSeenAt: components['schemas']['String']
      rootPath: string
    }
    RepositoryIcon: {
      contentUrl?: string | null
      fallbackColor: string
      fallbackText: string
      /** Format: uuid */
      repositoryId: string
    }
    SendMessageRequest: {
      attachmentIds: string[]
      /** Format: uuid */
      clientMessageId: string
      text: string
    }
    SendMessageResponse: {
      accepted: boolean
      message: components['schemas']['Message']
    }
    ServerEvent:
      | {
          payload: {
            /** Format: int64 */
            cursor: number
            resumed: boolean
          }
          /** @enum {string} */
          type: 'server.welcome'
        }
      | {
          payload: components['schemas']['CommandAccepted']
          /** @enum {string} */
          type: 'command.accepted'
        }
      | {
          payload: components['schemas']['CommandRejected']
          /** @enum {string} */
          type: 'command.rejected'
        }
      | {
          payload: components['schemas']['Conversation']
          /** @enum {string} */
          type: 'conversation.upserted'
        }
      | {
          payload: components['schemas']['ConversationTitleUpdated']
          /** @enum {string} */
          type: 'conversation.title_updated'
        }
      | {
          payload: components['schemas']['Message']
          /** @enum {string} */
          type: 'message.upserted'
        }
      | {
          payload: components['schemas']['MessageDelta']
          /** @enum {string} */
          type: 'message.delta'
        }
      | {
          payload: components['schemas']['MessageCompleted']
          /** @enum {string} */
          type: 'message.completed'
        }
      | {
          payload: {
            state: components['schemas']['SessionState']
          }
          /** @enum {string} */
          type: 'session.state_changed'
        }
      | {
          payload: components['schemas']['AgentActivityChanged']
          /** @enum {string} */
          type: 'agent.activity_changed'
        }
      | {
          payload: components['schemas']['SteeringQueueChanged']
          /** @enum {string} */
          type: 'steering.queue_changed'
        }
      | {
          payload: components['schemas']['WorkspaceUpdated']
          /** @enum {string} */
          type: 'workspace.updated'
        }
      | {
          payload: components['schemas']['RepositoriesUpdated']
          /** @enum {string} */
          type: 'repositories.updated'
        }
      | {
          payload: components['schemas']['Attachment']
          /** @enum {string} */
          type: 'attachment.updated'
        }
      | {
          payload: components['schemas']['NotificationTargetChanged']
          /** @enum {string} */
          type: 'notification_target.changed'
        }
      | {
          payload: {
            /** Format: int64 */
            cursor: number
          }
          /** @enum {string} */
          type: 'sync.reset_required'
        }
      | {
          payload: components['schemas']['ApiError']
          /** @enum {string} */
          type: 'error'
        }
      | {
          payload: {
            /** Format: uuid */
            request_id: string
          }
          /** @enum {string} */
          type: 'server.pong'
        }
    ServerEventEnvelope: components['schemas']['ServerEvent'] & {
      /** Format: uuid */
      conversationId?: string | null
      emittedAt: string
      /** Format: int64 */
      eventId?: number | null
      /** Format: int32 */
      version: number
    }
    SessionInterruptCommand: {
      /** Format: uuid */
      conversationId: string
      /** Format: uuid */
      requestId: string
    }
    /** @enum {string} */
    SessionState:
      | 'creating'
      | 'starting'
      | 'idle'
      | 'working'
      | 'compacting'
      | 'retrying'
      | 'crashed'
      | 'restoring'
      | 'interrupted'
      | 'stopped'
      | 'error'
    SteeringQueueChanged: {
      delivery: components['schemas']['MessageDelivery']
      /** Format: int64 */
      pending: number
    }
    String: string
    SyncResponse: {
      /** Format: int64 */
      cursor: number
      events: unknown[]
      resetRequired: boolean
    }
    /** @enum {string} */
    TitleMode: 'automatic' | 'manual'
    TranscriptionResponse: {
      text: string
    }
    UpdateConversationRequest: {
      /** Format: uuid */
      avatarAttachmentId?: string | null
      title?: string | null
    }
    WorkspaceUpdated: {
      workingDirectory: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
