/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/account/openai-usage': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['openai_weekly_usage']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/attachments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['attachments_upload']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/attachments/{id}/content': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['attachment_content']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/attachments/{id}/thumbnail': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['attachment_thumbnail']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/bootstrap': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['bootstrap']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/conversations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['conversations_list']
    put?: never
    post: operations['conversations_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/conversations/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['conversation_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['conversation_update']
    trace?: never
  }
  '/v1/conversations/{id}/abort': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['conversation_abort']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/conversations/{id}/agent': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['conversation_agent_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['conversation_agent_update']
    trace?: never
  }
  '/v1/conversations/{id}/archive': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['conversation_archive']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/conversations/{id}/compact': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['conversation_compact']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/conversations/{id}/messages': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['messages_list']
    put?: never
    post: operations['messages_send']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/conversations/{id}/restore': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['conversation_restore']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/health/live': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['health_live']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/health/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['health_ready']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/pairing/exchange': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['pairing_exchange']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/pairing/request': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['pairing_request']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/repositories/{id}/icon': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['repository_icon']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/sync': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['sync']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/transcriptions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['transcriptions_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @enum {string} */
    ActivityPhase: 'thinking' | 'working' | 'compacting' | 'retrying'
    AgentActivitiesReset: Record<string, never>
    AgentActivity: {
      createdAt: components['schemas']['String']
      /** Format: uuid */
      id: string
      /** Format: int64 */
      sequence: number
      summary: string
      updatedAt: components['schemas']['String']
    }
    AgentActivityChanged: {
      active: boolean
      phase: components['schemas']['ActivityPhase']
    }
    AgentModel: {
      /** Format: int64 */
      contextWindow: number
      id: string
      name: string
      provider: string
      reasoning: boolean
      supportedThinkingLevels: components['schemas']['ThinkingLevel'][]
    }
    AgentModelSelection: {
      modelId: string
      provider: string
    }
    AgentTask: {
      createdAt: components['schemas']['String']
      /** Format: uuid */
      id: string
      note?: string | null
      /** Format: int64 */
      sequence: number
      status: components['schemas']['AgentTaskStatus']
      text: string
      updatedAt: components['schemas']['String']
    }
    AgentTaskList: {
      createdAt: components['schemas']['String']
      /** Format: uuid */
      id: string
      /** Format: int64 */
      revision: number
      tasks: components['schemas']['AgentTask'][]
      title?: string | null
      updatedAt: components['schemas']['String']
    }
    AgentTaskListChanged: {
      taskList?: null | components['schemas']['AgentTaskList']
    }
    /** @enum {string} */
    AgentTaskStatus: 'pending' | 'in_progress' | 'completed' | 'blocked' | 'skipped'
    ApiError: {
      code: components['schemas']['ErrorCode']
      message: string
      requestId?: string | null
      retryable: boolean
    }
    Attachment: {
      /** Format: int64 */
      byteSize: number
      contentUrl: string
      createdAt: components['schemas']['String']
      fileName: string
      /** Format: int32 */
      height: number
      /** Format: uuid */
      id: string
      mimeType: string
      status: components['schemas']['AttachmentStatus']
      thumbnailUrl: string
      /** Format: int32 */
      width: number
    }
    AttachmentResponse: {
      attachment: components['schemas']['Attachment']
    }
    /** @enum {string} */
    AttachmentStatus: 'uploading' | 'ready' | 'attached' | 'failed' | 'deleted'
    Bootstrap: {
      conversations: components['schemas']['Conversation'][]
      /** Format: int64 */
      cursor: number
      device: components['schemas']['Device']
      /** Format: int32 */
      protocolVersion: number
    }
    ClientCommand:
      | (components['schemas']['ClientHello'] & {
          /** Format: int32 */
          version: number
        } & {
          /** @enum {string} */
          type: 'client.hello'
        })
      | (components['schemas']['MessageSendCommand'] & {
          /** Format: int32 */
          version: number
        } & {
          /** @enum {string} */
          type: 'message.send'
        })
      | (components['schemas']['SessionInterruptCommand'] & {
          /** Format: int32 */
          version: number
        } & {
          /** @enum {string} */
          type: 'session.interrupt'
        })
      | (components['schemas']['ClientPing'] & {
          /** Format: int32 */
          version: number
        } & {
          /** @enum {string} */
          type: 'client.ping'
        })
    ClientHello: {
      /** Format: uuid */
      deviceId: string
      /** Format: int64 */
      lastCursor: number
      /** Format: uuid */
      requestId: string
    }
    ClientPing: {
      /** Format: uuid */
      requestId: string
    }
    CommandAccepted: {
      message?: null | components['schemas']['Message']
      /** Format: uuid */
      requestId: string
    }
    CommandRejected: {
      error: components['schemas']['ApiError']
      /** Format: uuid */
      requestId: string
    }
    CompactConversationResponse: {
      /** Format: int64 */
      estimatedTokensAfter: number
      /** Format: int64 */
      tokensBefore: number
    }
    ContextUsage: {
      /** Format: int64 */
      contextWindow: number
      /** Format: double */
      percent?: number | null
      /** Format: int64 */
      tokens?: number | null
    }
    Conversation: {
      activeWorkingDirectory: string
      activities: components['schemas']['AgentActivity'][]
      archivedAt?: null | components['schemas']['String']
      createdAt: components['schemas']['String']
      /** Format: uuid */
      id: string
      lastMessageAt?: null | components['schemas']['String']
      /** Format: uuid */
      notificationTargetDeviceId?: string | null
      preview: string
      repositories: components['schemas']['Repository'][]
      state: components['schemas']['SessionState']
      taskList?: null | components['schemas']['AgentTaskList']
      title: string
      titleMode: components['schemas']['TitleMode']
      /** Format: int64 */
      unreadCount: number
      updatedAt: components['schemas']['String']
      /** Format: int64 */
      version: number
    }
    ConversationAgentState: {
      autoCompactionEnabled: boolean
      availableModels: components['schemas']['AgentModel'][]
      contextUsage?: null | components['schemas']['ContextUsage']
      model?: null | components['schemas']['AgentModel']
      thinkingLevel: components['schemas']['ThinkingLevel']
    }
    ConversationList: {
      conversations: components['schemas']['Conversation'][]
    }
    ConversationMessages: {
      messages: components['schemas']['Message'][]
      /** Format: int64 */
      nextBeforeOrdinal?: number | null
    }
    /** @enum {string} */
    ConversationScope: 'active' | 'archived' | 'all'
    ConversationTitleUpdated: {
      automatic: boolean
      title: string
    }
    CreateConversationRequest: Record<string, never>
    Device: {
      createdAt: components['schemas']['String']
      /** Format: uuid */
      id: string
      lastSeenAt: components['schemas']['String']
      name: string
      notificationsEnabled: boolean
      platform: components['schemas']['DevicePlatform']
    }
    /** @enum {string} */
    DevicePlatform: 'ios' | 'ipados' | 'web'
    /** @enum {string} */
    ErrorCode:
      | 'authentication_required'
      | 'forbidden'
      | 'invalid_request'
      | 'not_found'
      | 'conflict'
      | 'agent_unavailable'
      | 'agent_rejected'
      | 'attachment_invalid'
      | 'transcription_failed'
      | 'rate_limited'
      | 'internal_error'
    ErrorResponse: {
      error: components['schemas']['ApiError']
    }
    Message: {
      attachments: components['schemas']['Attachment'][]
      /** Format: uuid */
      clientMessageId?: string | null
      /** Format: uuid */
      conversationId: string
      createdAt: components['schemas']['String']
      delivery?: null | components['schemas']['MessageDelivery']
      /** Format: uuid */
      id: string
      /** Format: int64 */
      ordinal: number
      role: components['schemas']['MessageRole']
      /** Format: uuid */
      sentByDeviceId?: string | null
      status: components['schemas']['MessageStatus']
      text: string
      updatedAt: components['schemas']['String']
    }
    MessageCompleted: {
      /** Format: uuid */
      messageId: string
    }
    /** @enum {string} */
    MessageDelivery: 'initial' | 'steer' | 'bash'
    MessageDelta: {
      /** Format: int64 */
      chunkIndex: number
      delta: string
      /** Format: uuid */
      messageId: string
    }
    /** @enum {string} */
    MessageRole: 'user' | 'assistant'
    MessageSendCommand: {
      attachmentIds: string[]
      /** Format: uuid */
      clientMessageId: string
      /** Format: uuid */
      conversationId: string
      /** Format: uuid */
      requestId: string
      text: string
    }
    /** @enum {string} */
    MessageStatus:
      'pending' | 'accepted' | 'queued' | 'streaming' | 'completed' | 'interrupted' | 'failed'
    NotificationTargetChanged: {
      /** Format: uuid */
      deviceId: string
    }
    /** @enum {string} */
    OpenAiUsageAvailability: 'available' | 'stale' | 'unavailable'
    OpenAiWeeklyUsage: {
      availability: components['schemas']['OpenAiUsageAvailability']
      collectedAt?: string | null
      resetsAt?: string | null
      /** Format: int32 */
      usedPercent?: number | null
    }
    PairingCodeRequestResponse: {
      expiresAt: string
    }
    PairingExchangeRequest: {
      code: string
      deviceName: string
      platform: components['schemas']['DevicePlatform']
    }
    PairingExchangeResponse: {
      bootstrap: components['schemas']['Bootstrap']
      /** Format: uuid */
      deviceId: string
      token: string
    }
    RepositoriesUpdated: {
      repositories: components['schemas']['Repository'][]
    }
    Repository: {
      active: boolean
      branch?: string | null
      displayName: string
      firstSeenAt: components['schemas']['String']
      icon: components['schemas']['RepositoryIcon']
      /** Format: uuid */
      id: string
      lastSeenAt: components['schemas']['String']
      rootPath: string
    }
    RepositoryIcon: {
      contentUrl?: string | null
      fallbackColor: string
      fallbackText: string
      /** Format: uuid */
      repositoryId: string
    }
    SendMessageRequest: {
      attachmentIds: string[]
      /** Format: uuid */
      clientMessageId: string
      text: string
    }
    SendMessageResponse: {
      accepted: boolean
      message: components['schemas']['Message']
    }
    ServerEvent:
      | {
          payload: {
            /** Format: int64 */
            cursor: number
            resumed: boolean
          }
          /** @enum {string} */
          type: 'server.welcome'
        }
      | {
          payload: components['schemas']['CommandAccepted']
          /** @enum {string} */
          type: 'command.accepted'
        }
      | {
          payload: components['schemas']['CommandRejected']
          /** @enum {string} */
          type: 'command.rejected'
        }
      | {
          payload: components['schemas']['Conversation']
          /** @enum {string} */
          type: 'conversation.upserted'
        }
      | {
          payload: components['schemas']['ConversationTitleUpdated']
          /** @enum {string} */
          type: 'conversation.title_updated'
        }
      | {
          payload: components['schemas']['Message']
          /** @enum {string} */
          type: 'message.upserted'
        }
      | {
          payload: components['schemas']['MessageDelta']
          /** @enum {string} */
          type: 'message.delta'
        }
      | {
          payload: components['schemas']['MessageCompleted']
          /** @enum {string} */
          type: 'message.completed'
        }
      | {
          payload: {
            state: components['schemas']['SessionState']
          }
          /** @enum {string} */
          type: 'session.state_changed'
        }
      | {
          payload: components['schemas']['AgentActivityChanged']
          /** @enum {string} */
          type: 'agent.activity_changed'
        }
      | {
          payload: components['schemas']['AgentActivitiesReset']
          /** @enum {string} */
          type: 'agent.activities_reset'
        }
      | {
          payload: components['schemas']['AgentActivity']
          /** @enum {string} */
          type: 'agent.activity_upserted'
        }
      | {
          payload: components['schemas']['AgentTaskListChanged']
          /** @enum {string} */
          type: 'agent.task_list_changed'
        }
      | {
          payload: components['schemas']['SteeringQueueChanged']
          /** @enum {string} */
          type: 'steering.queue_changed'
        }
      | {
          payload: components['schemas']['WorkspaceUpdated']
          /** @enum {string} */
          type: 'workspace.updated'
        }
      | {
          payload: components['schemas']['RepositoriesUpdated']
          /** @enum {string} */
          type: 'repositories.updated'
        }
      | {
          payload: components['schemas']['Attachment']
          /** @enum {string} */
          type: 'attachment.updated'
        }
      | {
          payload: components['schemas']['NotificationTargetChanged']
          /** @enum {string} */
          type: 'notification_target.changed'
        }
      | {
          payload: {
            /** Format: int64 */
            cursor: number
          }
          /** @enum {string} */
          type: 'sync.reset_required'
        }
      | {
          payload: components['schemas']['ApiError']
          /** @enum {string} */
          type: 'error'
        }
      | {
          payload: {
            /** Format: uuid */
            request_id: string
          }
          /** @enum {string} */
          type: 'server.pong'
        }
    ServerEventEnvelope: components['schemas']['ServerEvent'] & {
      /** Format: uuid */
      conversationId?: string | null
      emittedAt: string
      /** Format: int64 */
      eventId?: number | null
      /** Format: int32 */
      version: number
    }
    SessionInterruptCommand: {
      /** Format: uuid */
      conversationId: string
      /** Format: uuid */
      requestId: string
    }
    /** @enum {string} */
    SessionState:
      | 'creating'
      | 'starting'
      | 'idle'
      | 'working'
      | 'compacting'
      | 'retrying'
      | 'crashed'
      | 'restoring'
      | 'interrupted'
      | 'stopped'
      | 'error'
    SteeringQueueChanged: {
      delivery: components['schemas']['MessageDelivery']
      /** Format: int64 */
      pending: number
    }
    String: string
    SyncResponse: {
      /** Format: int64 */
      cursor: number
      events: unknown[]
      resetRequired: boolean
    }
    /** @enum {string} */
    ThinkingLevel: 'off' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh' | 'max'
    /** @enum {string} */
    TitleMode: 'automatic' | 'manual'
    TranscriptionResponse: {
      text: string
    }
    UpdateConversationAgentRequest: {
      model?: null | components['schemas']['AgentModelSelection']
      thinkingLevel?: null | components['schemas']['ThinkingLevel']
    }
    UpdateConversationRequest: {
      /** Format: uuid */
      avatarAttachmentId?: string | null
      title?: string | null
    }
    WorkspaceUpdated: {
      workingDirectory: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  openai_weekly_usage: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OpenAiWeeklyUsage']
        }
      }
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiError']
        }
      }
    }
  }
  attachments_upload: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': string
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AttachmentResponse']
        }
      }
    }
  }
  attachment_content: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Original image bytes */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  attachment_thumbnail: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description JPEG thumbnail bytes */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  bootstrap: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Bootstrap']
        }
      }
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiError']
        }
      }
    }
  }
  conversations_list: {
    parameters: {
      query?: {
        /** @description Active, archived, or all conversations */
        scope?: components['schemas']['ConversationScope']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConversationList']
        }
      }
    }
  }
  conversations_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateConversationRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Conversation']
        }
      }
    }
  }
  conversation_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Conversation']
        }
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiError']
        }
      }
    }
  }
  conversation_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateConversationRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Conversation']
        }
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiError']
        }
      }
    }
  }
  conversation_abort: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The active Pi operation was interrupted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  conversation_agent_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConversationAgentState']
        }
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiError']
        }
      }
    }
  }
  conversation_agent_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateConversationAgentRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConversationAgentState']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiError']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiError']
        }
      }
    }
  }
  conversation_archive: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The conversation was archived */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  conversation_compact: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CompactConversationResponse']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiError']
        }
      }
    }
  }
  messages_list: {
    parameters: {
      query?: {
        beforeOrdinal?: number
        limit?: number
      }
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConversationMessages']
        }
      }
    }
  }
  messages_send: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SendMessageRequest']
      }
    }
    responses: {
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SendMessageResponse']
        }
      }
    }
  }
  conversation_restore: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Conversation']
        }
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiError']
        }
      }
    }
  }
  health_live: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The Luna process is alive */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  health_ready: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Luna storage and runtime dependencies are ready */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  pairing_exchange: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PairingExchangeRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PairingExchangeResponse']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiError']
        }
      }
    }
  }
  pairing_request: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PairingCodeRequestResponse']
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiError']
        }
      }
    }
  }
  repository_icon: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Detected repository icon bytes */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  sync: {
    parameters: {
      query?: {
        /** @description Last applied event cursor */
        after?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SyncResponse']
        }
      }
    }
  }
  transcriptions_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': string
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TranscriptionResponse']
        }
      }
    }
  }
}
